# site name
prefixName: Annie & Rex ğŸğŸ’
siteName: ğŸ«ğŸ„Our Story
# favicon and site master avatar
favicon: /Annie-and-Rex/images/favicon.ico
avatar: /Annie-and-Rex/images/head.jpg
url:
description: Please Take My Hand, Then We Can Travel To The MoonğŸŒ™
cdn:
pjax: 1
# 1å¼€å¯
mathjax: 0

notice: æ¬¢è¿åšå®¢ï¼è¯·éšä¾¿é€›é€›~
lazyloadImg:

menus:
  é¦–é¡µ: { path: /, fa: fa-fort-awesome faa-shake }
  å½’æ¡£: { path: /archives, fa: fa-archive faa-shake }
#  å½’æ¡£: { path: /archives, fa: fa-archive faa-shake, submenus: {
#    æŠ€æœ¯: {path: /categories/æŠ€æœ¯/, fa: fa-code },
#    ç”Ÿæ´»: {path: /categories/ç”Ÿæ´»/, fa: fa-file-text-o },
#    èµ„æº: {path: /categories/èµ„æº/, fa: fa-cloud-download },
#    éšæƒ³: {path: /categories/éšæƒ³/, fa: fa-commenting-o },
#    è½¬è½½: {path: /categories/è½¬è½½/, fa: fa-book }
#  } }
#  æ¸…å•: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: {
#    ä¹¦å•: {path: /tags/æ‚¦è¯»/, fa: fa-th-list faa-bounce },
#    ç•ªç»„: {path: /bangumi/, fa: fa-film faa-vertical },
#    æ­Œå•: {path: /music/, fa: fa-headphones },
#    å›¾é›†: {path: /tags/å›¾é›†/, fa: fa-photo }
#  } }
  ç•™è¨€æ¿: { path: /comment/, fa: fa-pencil-square-o faa-tada }
#  å‹äººå¸: { path: /links/, fa: fa-link faa-shake }
#  èµèµ: { path: /donate/, fa: fa-heart faa-pulse }
#  å…³äº: { path: /, fa: fa-leaf faa-wrench , submenus: {
#    æˆ‘ï¼Ÿ: {path: /about/, fa: fa-meetup},
#    ä¸»é¢˜: {path: /theme-sakura/, fa: iconfont icon-sakura },
#    Lab: {path: /lab/, fa: fa-cogs },
#  } }
#  å®¢æˆ·ç«¯: { path: /client/, fa: fa-android faa-vertical }
#  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }

# Home page sort type: -1: newer firstï¼Œ1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# èƒŒæ™¯å›¾ç‰‡ æ›´å¥½çš„ä¿®æ”¹
bg:
  - /Annie-and-Rex/images/cover/(0).jpg.webp
  - /Annie-and-Rex/images/cover/(1).jpg.webp
  - /Annie-and-Rex/images/cover/(2).jpg.webp
  - /Annie-and-Rex/images/cover/(3).jpg.webp
  - /Annie-and-Rex/images/cover/(4).jpg.webp
  - /Annie-and-Rex/images/cover/(5).jpg.webp
  - /Annie-and-Rex/images/cover/(6).jpg.webp
  - /Annie-and-Rex/images/cover/(7).jpg.webp
  - /Annie-and-Rex/images/cover/(8).jpg.webp

# èƒŒæ™¯å›¾ç‰‡æ ·å¼ ç©º åŸå›¾æ•ˆæœ filter-dim é˜´å½± filter-grid æ¨ªæ¡ filter-dot ç‚¹ç‚¹
bgclass: filter-grid

# startdash url, title, desc img
#startdash:
#  - {url: /theme-sakura/, title: Sakura, desc: æœ¬ç«™ hexo ä¸»é¢˜, img: /img/startdash/sakura.md.png}
#  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: åšä¸»çš„bç«™è§†é¢‘, img: /img/startdash/bilibili.jpg}
#  - {url: /, title: hojunçš„ä¸‡äº‹å±‹, desc: æŠ€æœ¯æœåŠ¡, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 02/14/2021

#social  url, img PCç«¯é…ç½®
social:
  #github: {url: http://github.com/honjun, img: /img/social/github.png}
  #sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  #wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
  #zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  #email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
  #wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img ç§»åŠ¨ç«¯é…ç½®
msocial:
  #github: {url: http://github.com/honjun, fa: fa-github, color: 333}
  #weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  #qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  #paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  #wechatSQ: /img/custom/donate/WeChanSQ.jpg

# è§†é¢‘åœ°å€ä¸ºhttps://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4ï¼Œé…ç½®å¦‚ä¸‹
movies:
  url: #https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # å¤šä¸ªè§†é¢‘ç”¨é€—å·éš”å¼€ï¼Œéšæœºè·å–ã€‚æ”¯æŒçš„æ ¼å¼ç›®å‰å·²çŸ¥MP4,Flvã€‚å…¶ä»–çš„å¯ä»¥è¯•ä¸‹ï¼Œä¸ä¿è¯æœ‰ç”¨
  name: #Unbroken.mp4

aplayer:
  id: 6710485831
  server: netease
  type: playlist
  fixed: true
  autoplay: true
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: isTIkptqJAV1sfzpMpCvsia7-gzGzoHsz
v_appKey: BL9EPI1VKJS2UTkjg8lwqHS9

